---
- name: <<<< Installing Pharo 3.0 on servers >>>>
  hosts: pharo
  serial: 5
  gather_facts: False

  vars:
    archiveName: pharo30.tar.gz

  tasks:
   - name: Deploy on servers
     copy: src={{ archiveName }} dest={{ destRemoteDir }}

   - name: Extract archive
     command: tar xfz {{ destRemoteDir }}/{{ archiveName }} --directory {{ destRemoteDir }}
     ignore_errors: True
